#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

#define _BL 0
#define _GBS 4
#define _GKP 5
#define _GSF 6
#define _FL 13
#define _KL 14
#define _RST  15


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
/* START BASE_LAYERS */
  /* Keymap _BL: Base Layer QWERTY (default)
   */
  [_BL] = LAYOUT(
    KC_GESC, KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    XXXXXXX,                   KC_EQL,          KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS,
    KC_GRV,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_LBRC,                   KC_RBRC,         KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_BSLS,
    KC_TAB,  KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_LPRN,                   KC_RPRN,         KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT,
    KC_LSPO, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    LCTL_T(KC_HOME),           RCTL_T(KC_PGUP), KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSPC,
    KC_LCTL, TT(_KL), XXXXXXX, KC_LGUI, KC_LALT, KC_BSPC, KC_DEL,  KC_END,  KC_PGDN, LT(_FL,KC_ENT),  KC_SPC,  KC_RALT, KC_RGUI, KC_APP,  TG(_GBS), KC_RCTL),

/* END BASE_LAYERS */

/* START GAMING_LAYERS
  /* Keymap _GAME_BASE: Base gaming layer
     Similar to base layout but left side set up for gaming */  
  [_GBS] = LAYOUT(
    _______,        _______, _______, _______, _______, _______, KC_6,                                  _______, _______, _______, _______, _______, _______, _______,
    _______,        _______, _______, _______, _______, _______, KC_7,                                  _______, _______, _______, _______, _______, _______, _______,
    LALT_T(KC_TAB), _______, _______, _______, _______, _______, KC_8,                                  _______, _______, _______, _______, _______, _______, _______,
    _______,        _______, _______, _______, _______, _______, LT(_GSF,KC_9),                         _______, _______, _______, _______, _______, _______, _______,
    _______,        _______, _______, _______, _______, KC_SPC,  LT(_GKP,KC_END), _______,     _______, _______, _______, _______, _______, _______, _______, _______),
  /* Keymap _GAME_KPD: Gaming Keypad layer
     Keypad on LHS */
  [_GKP] = LAYOUT(
    _______, _______, _______, _______, _______, _______, _______,                       _______, _______, _______, _______, _______, _______, _______,
    _______, KC_PDOT, KC_P7,   KC_P8,   KC_P9,   KC_PSLS, KC_P0,                         _______, _______, _______, _______, _______, _______, _______,
    _______, KC_PCMM, KC_P4,   KC_P5,   KC_P6,   KC_PAST, KC_PPLS,                       _______, _______, _______, _______, _______, _______, _______,
    _______, _______, KC_P1,   KC_P2,   KC_P3,   KC_PMNS, KC_PEQL,                       _______, _______, _______, _______, _______, _______, _______,
    _______, _______, _______, _______, _______, _______, _______, _______,     _______, _______, _______, _______, _______, _______, _______, _______),
  /* Keymap _GAME_SHIFT: Gaming Shifted layer
     FN Keys and other keys that moved */
  [_GSF] = LAYOUT(
    _______, KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,                         _______, _______, _______, _______, _______, _______, _______,
    _______, KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,                       _______, _______, _______, _______, _______, _______, _______,
    _______, _______, _______, _______, _______, _______, _______,                       _______, _______, _______, _______, _______, _______, _______,
    _______, _______, _______, _______, _______, _______, _______,                       _______, _______, _______, _______, _______, _______, _______,
    _______, _______, _______, _______, _______, _______, _______, _______,     _______, _______, _______, _______, _______, _______, _______, _______),

/* END GAMING_LAYERS */

/* START FUNCTIONAL LAYERS */
  /* Keymap _FL: Function Layer
     Function (Keys, Arrows and PSCR/BREAK cluster)
   */
  [_FL] = LAYOUT(
    _______, KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,                     KC_F7,           KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,  _______,
    _______, _______, _______, KC_UP,   _______, _______, _______,                   NK_OFF,          KC_CIRC, KC_PSCR, KC_SLCK, KC_PAUS, _______, _______,
    _______, _______, KC_LEFT, KC_DOWN, KC_RGHT, _______, _______,                   NK_ON,           _______, KC_INS,  KC_HOME, KC_PGUP, KC_COLN, _______,
    _______, KC_MPRV, KC_MPLY, KC_MPLY, KC_MNXT, _______, _______,                   NK_TOGG,         _______, KC_DEL,  KC_END,  KC_PGDN, _______, _______,
    _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,         _______, _______, _______, _______, _______, LT(_RST,XXXXXXX),
  /* Keymap _KL: Keypad Layer
     Provides keypad and shortcut to reset
   */
  [_KL] = LAYOUT(
    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,                   XXXXXXX,         XXXXXXX, KC_NLCK, KC_PSLS, KC_PAST, KC_PMNS, XXXXXXX,
    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, _______,                   _______,         XXXXXXX, KC_P7,   KC_P8,   KC_P9,   KC_PPLS, XXXXXXX,
    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, _______,                   _______,         XXXXXXX, KC_P4,   KC_P5,   KC_P6,   KC_PCMM, XXXXXXX,
    _______, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,                   XXXXXXX,         XXXXXXX, KC_P1,   KC_P2,   KC_P3,   KC_PEQL, _______,
    _______, TG(_KL),  XXXXXXX, XXXXXXX, XXXXXXX, _______, _______, XXXXXXX, XXXXXXX, KC_PENT,         KC_P0,   XXXXXXX, XXXXXXX, KC_PDOT, XXXXXXX, LT(_RST,XXXXXXX)),
  /*  Keymap _RST: Reset layer
   */
  [_RST] = LAYOUT(
    RESET,   XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,                   XXXXXXX,         XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, DEBUG,
    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,                   XXXXXXX,         XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,                   XXXXXXX,         XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,                   XXXXXXX,         XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,         XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX)
/* END FUNCTIONAL_LAYERS
};

